Importando bibliotecas

In [1]:
import gsidiag as gd
from datetime import datetime, timedelta
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

Definindo parâmetros para o uso do readDiag

In [2]:
#DIRdiag = "/home/patrick/readDiag/data"
DIRdiag = "/mnt/d/Dados/EXP21/gsi_dataout"
#D:\ftp1.cptec.inpe.br\pesquisa\das\joao.gerd\EXP18\GSI\dataout
varName = "amsua"
varType = "n15"
dateIni="2024030100" 
dateFin="2024030206" 
nHour = "6"          
vminOMA = -2.0       
vmaxOMA = 2.0        
vminSTD = 0.0        
vmaxSTD = 14.0       
Level = 1000
Lay = None           
SingleL = "All" 

datei = datetime.strptime(str(dateIni), "%Y%m%d%H")
datef = datetime.strptime(str(dateFin), "%Y%m%d%H")
dates = [dates.strftime('%Y%m%d%H') for dates in pd.date_range(datei, datef,freq="6H").tolist()]

print(dates)

['2024030100', '2024030106', '2024030112', '2024030118', '2024030200', '2024030206']

Encontrando e listando arquivos para serem usados

In [3]:
paths, pathsc = [], []

OuterL = "01"        
[paths.append(DIRdiag+"/"+dt+"/diag_amsua_n15_"+OuterL+"."+dt) for dt in dates]

OuterLc = "03"
[pathsc.append(DIRdiag+"/"+dt+"/diag_amsua_n15_"+OuterLc+"."+dt) for dt in dates]

print(paths)
print("")
print(pathsc)

['/mnt/d/Dados/EXP21/gsi_dataout/2024030100/diag_amsua_n15_01.2024030100', '/mnt/d/Dados/EXP21/gsi_dataout/2024030106/diag_amsua_n15_01.2024030106', '/mnt/d/Dados/EXP21/gsi_dataout/2024030112/diag_amsua_n15_01.2024030112', '/mnt/d/Dados/EXP21/gsi_dataout/2024030118/diag_amsua_n15_01.2024030118', '/mnt/d/Dados/EXP21/gsi_dataout/2024030200/diag_amsua_n15_01.2024030200', '/mnt/d/Dados/EXP21/gsi_dataout/2024030206/diag_amsua_n15_01.2024030206']

['/mnt/d/Dados/EXP21/gsi_dataout/2024030100/diag_amsua_n15_03.2024030100', '/mnt/d/Dados/EXP21/gsi_dataout/2024030106/diag_amsua_n15_03.2024030106', '/mnt/d/Dados/EXP21/gsi_dataout/2024030112/diag_amsua_n15_03.2024030112', '/mnt/d/Dados/EXP21/gsi_dataout/2024030118/diag_amsua_n15_03.2024030118', '/mnt/d/Dados/EXP21/gsi_dataout/2024030200/diag_amsua_n15_03.2024030200', '/mnt/d/Dados/EXP21/gsi_dataout/2024030206/diag_amsua_n15_03.2024030206']

Lendo arquivos listado usando o readDiag e concatenando os dados

In [4]:
# Define uma variável booleana 'read' como True para indicar que a leitura dos arquivos será realizada
read = True

# Verifica se 'read' é True para prosseguir com a leitura dos arquivos
if read:        
    # Inicializa uma lista vazia para armazenar os objetos gdf
    gdf_list = []
    # Imprime uma mensagem informando o tempo estimado necessário para a leitura dos arquivos
    print("")
    print("Aguarde, o tempo total estimado para a leitura dos arquivos é de "+
          str(int((float(len(paths))*20 )/60))+" minutos e "+
          str(int((float(len(paths))*20 )%60))+" segundos.")
    print("")
    # Itera sobre os caminhos dos arquivos e seus caminhos de configuração correspondentes
    for path, pathc in zip(paths,pathsc):
        # Imprime uma mensagem indicando o arquivo que está sendo lido
        print("Reading "+path)
        # Lê o arquivo usando a função read_diag do módulo gsidiag e armazena o objeto retornado em gdf
        gdf = gd.read_diag(path,pathc)
        # Adiciona o objeto gdf à lista gdf_list
        gdf_list.append(gdf)

    # Imprime a lista de objetos gdf lidos
    print(gdf_list)
    
    # Define uma string separadora para uso posterior
    separator = " ====================================================================================================="

Aguarde, o tempo total estimado para a leitura dos arquivos é de 2 minutos e 0 segundos.

Reading /mnt/d/Dados/EXP21/gsi_dataout/2024030100/diag_amsua_n15_01.2024030100

>>> GSI DIAG <<<

Reading /mnt/d/Dados/EXP21/gsi_dataout/2024030106/diag_amsua_n15_01.2024030106

>>> GSI DIAG <<<

Reading /mnt/d/Dados/EXP21/gsi_dataout/2024030112/diag_amsua_n15_01.2024030112

>>> GSI DIAG <<<

Reading /mnt/d/Dados/EXP21/gsi_dataout/2024030118/diag_amsua_n15_01.2024030118

>>> GSI DIAG <<<

Reading /mnt/d/Dados/EXP21/gsi_dataout/2024030200/diag_amsua_n15_01.2024030200

>>> GSI DIAG <<<

Reading /mnt/d/Dados/EXP21/gsi_dataout/2024030206/diag_amsua_n15_01.2024030206

>>> GSI DIAG <<<

[<gsidiag.__main__.read_diag object at 0x7fa310770350>, <gsidiag.__main__.read_diag object at 0x7fa29caf2610>, <gsidiag.__main__.read_diag object at 0x7fa2a084d190>, <gsidiag.__main__.read_diag object at 0x7fa29ff5ce50>, <gsidiag.__main__.read_diag object at 0x7fa29656ef90>, <gsidiag.__main__.read_diag object at 0x7fa292446b90>]

In [5]:
# Inicialização de DataFrame vazio para armazenar dados concatenados
df_concatenado2 = pd.DataFrame()

# Iteração sobre objetos em gdf_list
for objeto in gdf_list:
        
    print(separator)
    print("Separando dados do arquivo" + str(objeto._diagFile))
    
    # Criação de dicionário de dados a partir do objeto   
    dados_dict = {
            'lat': objeto.obsInfo[varName].loc[varType].lat,
            'lon': objeto.obsInfo[varName].loc[varType].lon,
            'elev': objeto.obsInfo[varName].loc[varType].elev,
            'nchan': objeto.obsInfo[varName].loc[varType].nchan,
            'time': objeto.obsInfo[varName].loc[varType].time,
            'iuse': objeto.obsInfo[varName].loc[varType].iuse,
            'idqc': objeto.obsInfo[varName].loc[varType].idqc,
            'inverr': objeto.obsInfo[varName].loc[varType].inverr,
            'oer': objeto.obsInfo[varName].loc[varType].oer,
            'obs': objeto.obsInfo[varName].loc[varType].obs,
            'omf': objeto.obsInfo[varName].loc[varType].omf,
            'omf_nobc': objeto.obsInfo[varName].loc[varType].omf_nobc,
            'emiss': objeto.obsInfo[varName].loc[varType].emiss,
            'oma': objeto.obsInfo[varName].loc[varType].oma,
            'oma_nobc': objeto.obsInfo[varName].loc[varType].oma_nobc,
            'imp': objeto.obsInfo[varName].loc[varType].imp,
            'dfs': objeto.obsInfo[varName].loc[varType].dfs
            }
        
    # Conversão do dicionário em DataFrame
    df_objeto = pd.DataFrame(dados_dict)
        
    # Concatenação do DataFrame do objeto com o DataFrame concatenado
    df_concatenado2 = pd.concat([df_concatenado2, df_objeto], ignore_index=True)

 =====================================================================================================
Separando dados do arquivo/mnt/d/Dados/EXP21/gsi_dataout/2024030100/diag_amsua_n15_01.2024030100
 =====================================================================================================
Separando dados do arquivo/mnt/d/Dados/EXP21/gsi_dataout/2024030106/diag_amsua_n15_01.2024030106
 =====================================================================================================
Separando dados do arquivo/mnt/d/Dados/EXP21/gsi_dataout/2024030112/diag_amsua_n15_01.2024030112
 =====================================================================================================
Separando dados do arquivo/mnt/d/Dados/EXP21/gsi_dataout/2024030118/diag_amsua_n15_01.2024030118
 =====================================================================================================
Separando dados do arquivo/mnt/d/Dados/EXP21/gsi_dataout/2024030200/diag_amsua_n15_01.2024030200
 =====================================================================================================
Separando dados do arquivo/mnt/d/Dados/EXP21/gsi_dataout/2024030206/diag_amsua_n15_01.2024030206

In [10]:
tidx = 0
gdf_list[tidx].pfileinfo()

Variable Name : amsua
              └── kx => n15

In [11]:
gdf_list[tidx].obsInfo

{'amsua':                     lat         lon         elev  nchan      time  iuse  \
 SatId points
 n15   0      -87.575104   23.366800  2759.021729    1.0 -0.133056   1.0
       1      -87.575104   23.366800  2759.021729    2.0 -0.133056   1.0
       2      -87.575104   23.366800  2759.021729    3.0 -0.133056   1.0
       3      -87.575104   23.366800  2759.021729    4.0 -0.133056   1.0
       4      -87.575104   23.366800  2759.021729    5.0 -0.133056   1.0
 ...                 ...         ...          ...    ...       ...   ...
       128740 -50.419899  336.121613     0.048680   11.0 -1.643056  -1.0
       128741 -50.419899  336.121613     0.048680   12.0 -1.643056   1.0
       128742 -50.419899  336.121613     0.048680   13.0 -1.643056   1.0
       128743 -50.419899  336.121613     0.048680   14.0 -1.643056  -1.0
       128744 -50.419899  336.121613     0.048680   15.0 -1.643056   1.0

                     idqc        inverr           oer           obs  \
 SatId points
 n15   0        50.000000  0.000000e+00           NaN  1.862300e+02
       1         0.000000 -4.451865e+00           NaN  1.000000e+10
       2         3.928810  1.067861e+00  7.367746e+00  0.000000e+00
       3         6.175547  2.220000e+02  4.504505e-03  2.742377e-01
       4       227.050003  1.000000e+10  1.000000e-10 -6.690545e-01
 ...                  ...           ...           ...           ...
       128740    0.299281  2.001880e-01  4.995304e+00  0.000000e+00
       128741    0.200188  0.000000e+00           NaN -3.192612e+00
       128742    0.000000  0.000000e+00           NaN  3.982687e-01
       128743    0.000000  0.000000e+00           NaN  0.000000e+00
       128744    0.000000 -7.111880e+00           NaN  0.000000e+00

                        omf      omf_nobc      emiss           oma  \
 SatId points
 n15   0      -1.849453e+00 -3.802883e+00   0.000000 -3.345131e+00
       1       1.859300e+02 -3.773708e+00  50.000000  1.859300e+02
       2       1.000000e+10  2.075000e+02   0.000000  1.000000e+10
       3       0.000000e+00  1.000000e+10   2.610525  0.000000e+00
       4      -7.919140e-02  0.000000e+00   4.266504 -7.690419e-02
 ...                    ...           ...        ...           ...
       128740  0.000000e+00  0.000000e+00   0.447424  0.000000e+00
       128741  0.000000e+00  0.000000e+00   0.299281  0.000000e+00
       128742  6.310853e-01  0.000000e+00   0.200188  3.597375e-01
       128743  2.394455e-01 -4.893317e-01   0.000000  6.957597e-01
       128744  0.000000e+00  5.057884e+01   0.000000  0.000000e+00

                   oma_nobc         imp         dfs  \
 SatId points
 n15   0      -5.382836e+00         NaN         NaN
       1      -3.105994e+00         NaN         NaN
       2       2.075000e+02        0.00        0.00
       3       1.000000e+10        0.00        0.00
       4       0.000000e+00 -3570243.75 -1811278.75
 ...                    ...         ...         ...
       128740  0.000000e+00        0.00        0.00
       128741  0.000000e+00         NaN         NaN
       128742  0.000000e+00         NaN         NaN
       128743 -8.341221e-01         NaN         NaN
       128744  5.135218e+01         NaN         NaN

                                  geometry
 SatId points
 n15   0        POINT (23.36681 -87.57510)
       1        POINT (23.36681 -87.57510)
       2        POINT (23.36681 -87.57510)
       3        POINT (23.36681 -87.57510)
       4        POINT (23.36681 -87.57510)
 ...                                   ...
       128740  POINT (-23.87842 -50.41990)
       128741  POINT (-23.87842 -50.41990)
       128742  POINT (-23.87842 -50.41990)
       128743  POINT (-23.87842 -50.41990)
       128744  POINT (-23.87842 -50.41990)

 [128745 rows x 18 columns]}

In [12]:
print('Variável: ', varName)

gdf_list[tidx].obsInfo[varName]

Variável:  amsua

                    lat         lon         elev  nchan      time  iuse  \
SatId points
n15   0      -87.575104   23.366800  2759.021729    1.0 -0.133056   1.0
      1      -87.575104   23.366800  2759.021729    2.0 -0.133056   1.0
      2      -87.575104   23.366800  2759.021729    3.0 -0.133056   1.0
      3      -87.575104   23.366800  2759.021729    4.0 -0.133056   1.0
      4      -87.575104   23.366800  2759.021729    5.0 -0.133056   1.0
...                 ...         ...          ...    ...       ...   ...
      128740 -50.419899  336.121613     0.048680   11.0 -1.643056  -1.0
      128741 -50.419899  336.121613     0.048680   12.0 -1.643056   1.0
      128742 -50.419899  336.121613     0.048680   13.0 -1.643056   1.0
      128743 -50.419899  336.121613     0.048680   14.0 -1.643056  -1.0
      128744 -50.419899  336.121613     0.048680   15.0 -1.643056   1.0

                    idqc        inverr           oer           obs  \
SatId points
n15   0        50.000000  0.000000e+00           NaN  1.862300e+02
      1         0.000000 -4.451865e+00           NaN  1.000000e+10
      2         3.928810  1.067861e+00  7.367746e+00  0.000000e+00
      3         6.175547  2.220000e+02  4.504505e-03  2.742377e-01
      4       227.050003  1.000000e+10  1.000000e-10 -6.690545e-01
...                  ...           ...           ...           ...
      128740    0.299281  2.001880e-01  4.995304e+00  0.000000e+00
      128741    0.200188  0.000000e+00           NaN -3.192612e+00
      128742    0.000000  0.000000e+00           NaN  3.982687e-01
      128743    0.000000  0.000000e+00           NaN  0.000000e+00
      128744    0.000000 -7.111880e+00           NaN  0.000000e+00

                       omf      omf_nobc      emiss           oma  \
SatId points
n15   0      -1.849453e+00 -3.802883e+00   0.000000 -3.345131e+00
      1       1.859300e+02 -3.773708e+00  50.000000  1.859300e+02
      2       1.000000e+10  2.075000e+02   0.000000  1.000000e+10
      3       0.000000e+00  1.000000e+10   2.610525  0.000000e+00
      4      -7.919140e-02  0.000000e+00   4.266504 -7.690419e-02
...                    ...           ...        ...           ...
      128740  0.000000e+00  0.000000e+00   0.447424  0.000000e+00
      128741  0.000000e+00  0.000000e+00   0.299281  0.000000e+00
      128742  6.310853e-01  0.000000e+00   0.200188  3.597375e-01
      128743  2.394455e-01 -4.893317e-01   0.000000  6.957597e-01
      128744  0.000000e+00  5.057884e+01   0.000000  0.000000e+00

                  oma_nobc         imp         dfs  \
SatId points
n15   0      -5.382836e+00         NaN         NaN
      1      -3.105994e+00         NaN         NaN
      2       2.075000e+02        0.00        0.00
      3       1.000000e+10        0.00        0.00
      4       0.000000e+00 -3570243.75 -1811278.75
...                    ...         ...         ...
      128740  0.000000e+00        0.00        0.00
      128741  0.000000e+00         NaN         NaN
      128742  0.000000e+00         NaN         NaN
      128743 -8.341221e-01         NaN         NaN
      128744  5.135218e+01         NaN         NaN

                                 geometry
SatId points
n15   0        POINT (23.36681 -87.57510)
      1        POINT (23.36681 -87.57510)
      2        POINT (23.36681 -87.57510)
      3        POINT (23.36681 -87.57510)
      4        POINT (23.36681 -87.57510)
...                                   ...
      128740  POINT (-23.87842 -50.41990)
      128741  POINT (-23.87842 -50.41990)
      128742  POINT (-23.87842 -50.41990)
      128743  POINT (-23.87842 -50.41990)
      128744  POINT (-23.87842 -50.41990)

[128745 rows x 18 columns]

In [6]:
print(df_concatenado2)

              lat         lon         elev  nchan      time  iuse        idqc  \
0      -87.575104   23.366800  2759.021729    1.0 -0.133056   1.0   50.000000
1      -87.575104   23.366800  2759.021729    2.0 -0.133056   1.0    0.000000
2      -87.575104   23.366800  2759.021729    3.0 -0.133056   1.0    3.928810
3      -87.575104   23.366800  2759.021729    4.0 -0.133056   1.0    6.175547
4      -87.575104   23.366800  2759.021729    5.0 -0.133056   1.0  227.050003
...           ...         ...          ...    ...       ...   ...         ...
758725  82.669998  359.121704     0.142100   11.0  2.725833  -1.0    0.299281
758726  82.669998  359.121704     0.142100   12.0  2.725833   1.0    0.200188
758727  82.669998  359.121704     0.142100   13.0  2.725833   1.0    0.000000
758728  82.669998  359.121704     0.142100   14.0  2.725833  -1.0    0.000000
758729  82.669998  359.121704     0.142100   15.0  2.725833   1.0    0.000000

              inverr           oer           obs           omf      omf_nobc  \
0       0.000000e+00           NaN  1.862300e+02 -1.849453e+00 -3.802883e+00
1      -4.451865e+00           NaN  1.000000e+10  1.859300e+02 -3.773708e+00
2       1.067861e+00  7.367746e+00  0.000000e+00  1.000000e+10  2.075000e+02
3       2.220000e+02  4.504505e-03  2.742377e-01  0.000000e+00  1.000000e+10
4       1.000000e+10  1.000000e-10 -6.690545e-01 -7.919140e-02  0.000000e+00
...              ...           ...           ...           ...           ...
758725  2.001880e-01  4.995304e+00  0.000000e+00  0.000000e+00  0.000000e+00
758726  0.000000e+00           NaN -4.978413e+00  0.000000e+00  0.000000e+00
758727  0.000000e+00           NaN  5.704956e+00 -2.388505e+00  0.000000e+00
758728  0.000000e+00           NaN  0.000000e+00  2.309338e+01 -4.805557e+00
758729 -1.530918e+01           NaN  0.000000e+00  0.000000e+00  2.343711e+02

            emiss           oma      oma_nobc         imp         dfs
0        0.000000 -3.345131e+00 -5.382836e+00         NaN         NaN
1       50.000000  1.859300e+02 -3.105994e+00         NaN         NaN
2        0.000000  1.000000e+10  2.075000e+02        0.00        0.00
3        2.610525  0.000000e+00  1.000000e+10        0.00        0.00
4        4.266504 -7.690419e-02  0.000000e+00 -3570243.75 -1811278.75
...           ...           ...           ...         ...         ...
758725   0.447424  0.000000e+00  0.000000e+00        0.00        0.00
758726   0.299281  0.000000e+00  0.000000e+00         NaN         NaN
758727   0.200188 -2.595019e+00  0.000000e+00         NaN         NaN
758728   0.000000  1.663323e+01 -4.078386e+00         NaN         NaN
758729   0.000000  0.000000e+00  1.576890e+02         NaN         NaN

[758730 rows x 17 columns]

In [13]:
# Remoção de linhas com valores NaN
df_concatenado2.dropna(inplace=True)

# Filtrando os canais sub-representados
df_concatenado2 = df_concatenado2[~df_concatenado2['nchan'].isin([1, 2, 3, 4, 5, 15])]

print(df_concatenado2)

print(separator)

              lat         lon         elev  nchan      time  iuse      idqc  \
6      -87.575104   23.366800  2759.021729    7.0 -0.133056   1.0  0.000000
8      -87.575104   23.366800  2759.021729    9.0 -0.133056   1.0 -0.669055
10     -87.575104   23.366800  2759.021729   11.0 -0.133056  -1.0 -0.299492
21     -87.072800   14.031500  2703.247070    7.0 -1.808611   1.0  0.000000
23     -87.072800   14.031500  2703.247070    9.0 -1.808611   1.0 -0.669055
...           ...         ...          ...    ...       ...   ...       ...
758710  81.331596  355.833893    -1.787692   11.0  2.732500  -1.0  0.299281
758722  82.669998  359.121704     0.142100    8.0  2.725833   1.0  0.329504
758723  82.669998  359.121704     0.142100    9.0  2.725833   1.0  0.668897
758724  82.669998  359.121704     0.142100   10.0  2.725833   1.0  0.447424
758725  82.669998  359.121704     0.142100   11.0  2.725833  -1.0  0.299281

          inverr       oer       obs       omf  omf_nobc         emiss  \
6       0.435375  2.296868 -0.299492  0.447634 -0.669055  1.000000e+10
8       0.447634  2.233968  0.075320  0.200376 -0.299492  9.503246e-02
10      0.200376  4.990614  0.000000  0.000000  0.000000  4.476340e-01
21      0.435375  2.296868 -0.299492  0.447634 -0.669055  1.000000e+10
23      0.447634  2.233968  0.072090  0.200376 -0.299492  9.503246e-02
...          ...       ...       ...       ...       ...           ...
758710  0.200188  4.995304  0.000000  0.000000  0.000000  4.474238e-01
758722  0.668897  1.494998  0.200188  0.299281  0.447424  0.000000e+00
758723  0.447424  2.235018  0.000000  0.200188  0.299281 -1.123915e-01
758724  0.299281  3.341346  0.000000  0.000000  0.200188  6.688974e-01
758725  0.200188  4.995304  0.000000  0.000000  0.000000  4.474238e-01

             oma  oma_nobc  imp  dfs
6       0.447634 -0.669055  0.0  0.0
8       0.200376 -0.299492  0.0  0.0
10      0.000000  0.000000  0.0  0.0
21      0.447634 -0.669055  0.0  0.0
23      0.200376 -0.299492  0.0  0.0
...          ...       ...  ...  ...
758710  0.000000  0.000000  0.0  0.0
758722  0.299281  0.447424  0.0  0.0
758723  0.200188  0.299281  0.0  0.0
758724  0.000000  0.200188  0.0  0.0
758725  0.000000  0.000000  0.0  0.0

[98288 rows x 17 columns]
 =====================================================================================================